# Config file used for Prediction and Image manipulation
# (c) 2024 Yonz
# License: No License


# --- Roboflow ---
Roboflow:
  API_KEY: "IOgzRx9sitOu5Sz6YTOC"
  SERVER_URL: "http://172.30.32.0:9001/"
  WORKSPACE_NAME: "meterreader"
  PROJECT_NAME_FRAME: "meter-frame2"
  PROJECT_NAME_COUNTERS: "meter-counter-inner-box"
  PROJECT_NAME_DIGITS: "meter-digits-itvsi"
  VERSION_FRAME: "1"
  VERSION_COUNTERS: "3"
  VERSION_DIGITS: "5"
  YOLO_WEIGHTS_DIR: "../weights"

# --- Mongo Database ---
MongoDB:
  URI: "mongodb://172.30.32.2:27017/"
  database: "meterreader"
  collection: "image_metadata"


# --- Image Manipulation ---
ImageManipulation:
  DEFAULT_CONFIDENCE: 66
  DEFAULT_OVERLAP: 10
  DEFAULT_MERGE_PARALLEL: true
  DEFAULT_DISPLAY_IMAGE: false
  DEFAULT_DEBUG: false
  DEFAULT_FILEPATH: "./static/"
  EXPAND_BBOX_BY: 1.03
  INCREASE_CONFIDENCE_BY: 1.2
  DEFAULT_MAX_HEIGHT: 1280
  canny_threshold1: 120
  canny_threshold2: 250
  digit_min_height: 20
  digit_max_height: 40
  digit_y_alignment: 10


# --- YOLO ---
YOLO:
  device: "cpu"
  weights_path: "./weights"
  weights:
    frame: "meter-frame.pt"
    counter: "meter-counter.pt"
    digits:  "meter-digits.pt"


# --- MQTT ---
MQTT:
  broker: dokkan.zt     # The hostname or IP address of your MQTT broker
  port: 1883            # The port used by your MQTT broker
  username: mqtt_user   # Your MQTT username
  password: Dokkan2025  # Your MQTT password
  topic: homeassistant/sensor  # The base topic for MQTT messages
  tracked_devices:      # A list of devices to track
    - electricity_meter # Add more devices as needed
  birth_topic:  homeassistant/status
  birth_payload: online
  will_topic: homeassistant/status
  will_payload: offline

  # Template for Homeassitant device configuration (Device Discovery)
  # See: https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery
  # Note: use render-yaml.py script to render the device/sensor config using a pre-defined YMAL/JINJA2 template
  devices:
    my_meter:
      name: "my_meter"
      state_topic: "homeassistant/sensor/my_meter/state"
      unique_id: "my_meter_UID"
      object_id: "my_meter_OBJ"
      icon: "mdi:meter-electric"  # Default icon
      availability_topic: "homeassistant/sensor/my_meter/status"  # Default LWT topic
      device_class: "energy"

      state_class: "total_increasing"
      friendly_name: "my_meter_FRIENDLY"
      unit_of_measurement: "kWh"
      value_template: "{{ value_json.value }}"

      #
      # The followng is only needed once per device. If there are multiple states or attributes being defined, 
      # only send the "main_device" configuration once

      device:
        identifiers:
          - "my_meter"
        name: "my_meter"
        manufacturer: "4Pi"  # Default manufacturer
        model: "4PI"  # Default model
        hw_version: "virtual_01"  # Default hardware version
        sw_version: "0.8.0"  # Default software version
          # Default empty config URL

