services:
  meterreader:
    image: meterreader
    container_name: meterreader
    hostname: meterreader
    domainname: docker
    networks:
      - app_network
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - linux/amd64
        #- linux/arm64

    ports:
      - 8099:8099
    restart: no
    environment:
      FLASK_APP: server.py
      QUART_ENV: development
      QUART_DEBUG: 1
      LOG_DIR: /usr/src/app/log
      LOG_LEVEL: DEBUG
      LOGGER_NAME: MeterReader
      CONFIG_FILE: "/usr/src/app/config.yaml"
    volumes: 
      - /var/data/meterreader/log:/usr/src/app/log
      - /var/data/meterreader/weights:/usr/src/app/weights
      - /var/data/meterreader/templates:/usr/src/app/templates
      - /var/data/meterreader/static:/usr/src/app/static

networks:
   app_network:
     external: true      
      