FROM python:3.12.8-bookworm

WORKDIR /usr/src/app
EXPOSE 8099

COPY *.py .

RUN adduser -u 5678 --disabled-password --gecos "" appuser
RUN chown -R appuser /usr/src/app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["ls -la" ]
