# MQTT Broker Configuration
mqtt_broker: dokkan.zt  # The hostname or IP address of your MQTT broker
mqtt_port: 1883        # The port used by your MQTT broker

# MQTT Credentials
mqtt_username: mqtt_user    # Your MQTT username
mqtt_password: Dokkan2025  # Your MQTT password

# MQTT Topic
mqtt_topic: homeassistant/sensor  # The base topic for MQTT messages

# Tracked Devices
tracked_devices:           # A list of devices to track
  - electricity_meter       # Add more devices as needed